feat: react shopping cart step 1 구현
liswktjs/ts-shopping-cart pull request #1
Opened 2024-05-04 15:18 UTC by liswktjs

## 구현 사항 

- 상품 목록 페이지 (메인 페이지) 
- 상품 상세 페이지 

## 구현하지 못한 부분 

- api pending중에 보여줄 loading 화면 

## 새롭게 시도해본 라이브러리

- styleX

2024-05-06 05:57 UTC, soyi47 requested changes
연휴에도 고생이 많으십니다 껄껄

리드미도, 그리고 모킹 서버도 잘 챙겨주셨군요. 역시 꼼꼼샐리 💖

폴더 구조/네이밍에 대한 질문 확인 부탁드려요!

2024-05-06 05:57 UTC, soyi47 commented on README.md
> +
로컬 실행 방법 챙겨주셔서 감사합니다!! 👍

2024-05-06 05:57 UTC, soyi47 commented on README.md
> +### pages
폴더명이 파스칼케이스랑 케밥이 섞여 있는 것 같은데 의도한 것인가요? 다르게 네이밍 규칙을 둔 기준이 무엇인가요?

- Layout, Pages,Router는 대문자로 시작
- shared, styles는 소문자로 시작

2024-05-06 05:57 UTC, soyi47 commented on index.html
>    </head>
타이틀도 챙겨주세욤~

2024-05-06 05:57 UTC, soyi47 commented on src/Router/index.tsx
> +    },
동일한 레이아웃 사용하고 있어서 react-router-dom의 Outlet 이용해서 Layout을 한번에 적용해도 좋을 것 같아요.

https://reactrouter.com/en/main/components/outlet

2024-05-06 05:57 UTC, soyi47 commented on src/Layout/index.tsx
> +export default Layout;
이 아이도 shared Component라고 볼 수 있을 것 같은데 따로 빼둔 이유가 있을까요? 

아니면 router에서만 사용되니 router 폴더에 같이 있는 게 조금 더 자연스러울 것 같다고 생각합니다.

2024-05-06 05:57 UTC, soyi47 commented on src/Pages/ProductDetail.tsx
> +  },
전체적으로 스타일 코드 파일 분리해주면 좋을 것 같습니다!

2024-05-06 05:57 UTC, soyi47 commented on src/Pages/ProductDetail.tsx
> +      {...stylex.props(style.container)}
스타일엑스는 클래스 네임 적용하는 방법이 이 방법 뿐인가요..? 명시적으로 보이게 className에 넣어주면 방식이면 좋을텐데..!

```
className={stylex.props(style.container).className}
```

이게 조금 나아보이지만... 애매하네요

2024-05-06 05:57 UTC, soyi47 commented on src/shared/components/Text/index.tsx
> +};
Button이랑 Text 공용 컴포넌트 좋네요 👍

2024-05-06 05:57 UTC, soyi47 commented on src/shared/components/Text/index.tsx
> +  zinc_500_xl_bold: {
zinc는 무슨 뜻인가욤? 이것도 색깔 이름인가..?

2024-05-06 05:57 UTC, soyi47 commented on src/styles/font.css
> +  font-family: "Hahmlet", serif;
폰트 예쁜 걸로 챙겼군요 🥹

2024-05-06 05:57 UTC, soyi47 commented on src/shared/product/api/key.ts
> +};
폴더 구조가 어색하게 느껴지는데요.
shared 폴더 밑에 product 라는 도메인이 또 하나 있는 부분이 그렇습니다.

shared/components, shared/constant와 shared/product는 분리 기준이 다른 것도 같고요.
컴포넌트를 봐서는 shared의 개념이 상품, 장바구니 요런 개념과 상관없이 쓰일 수 있는 영역에 속한 요소들을 모아둔 것 같은데,
밑에 product가 또 들어가니 shared로 상위에서 분리해둔 의미가 없어지는 것 같습니다.  (shared/cart 요런 식으로 또 추가되는 방향을 생각하신 걸까요?)

샐리가 다르게 예상한 폴더 구조의 발전 방향이 있을까요? 한번 다시 보면 좋을 것 같아요!

2024-05-06 05:57 UTC, soyi47 commented on src/shared/product/api/queries/useGetInfiniteProductList.ts
> +    });
ㅎ.. 난 스크롤 로드 적용 안 했던 것 같은데 .. 해야겠꾼 😇

2024-05-15 14:14 UTC, liswktjs commented on README.md
> +### pages
아하 차이점을 둔 이유는 

-  Layout, Pages, Router
의 경우에는 리액트 내에서 집을 짓는 토대가 되어 
각기 중요한 뼈대들로 동작 하고 있기 때문에 이를 구별짓기 위해 대문자로 
- shared, styles, feature
의 경우에는 주로 재사용 기능이나 pages들 내부의 부속품으로 동작하고 있어 케밥케이스로  폴더명을 명명하여 폴더별로 역할과 중요도를 나눠보려고 시도를 한 번 해보았습니다

2024-05-15 14:16 UTC, liswktjs commented on index.html
>    </head>
예리하시군요 잊고있었네요
<a href="https://github.com/liswktjs/ts-shopping-cart/pull/1/commits/62b6b4ee12ff1d35fa295d02f73cb8a06b14aacf">여기</a> 반영했습니당!

2024-05-15 14:17 UTC, liswktjs commented on src/Router/index.tsx
> +    },
오호 좋은 그런 방법도 있었네요 
잠시 next와 자주 놀아서 잊고 있었네요

2024-05-23 14:59 UTC, liswktjs commented on src/Router/index.tsx
> +    },
[b381a8e](https://github.com/liswktjs/ts-shopping-cart/pull/1/commits/b381a8e6fbb69a16d36b2432c1b1c72f694fcef1) 여기 반영했습니다!

2024-05-23 15:04 UTC, liswktjs commented on src/Layout/index.tsx
> +export default Layout;
아 앞서 대소문자 폴더명 나눈 것과 더불어서 이어져서 (이제는 Outlet 반영으로) 
한 번의 선언으로 전체 페이지간에 적용되는 컴포넌트이기 때문에 
작은 단위로 여러번 사용되는 shared component 위치에 위치시키는 것은 애매하다고 생각해서 Layout으로 따로 분리했습니다!

2024-05-23 15:09 UTC, liswktjs commented on src/Pages/ProductDetail.tsx
> +  },
> https://stylexjs.com/docs/learn/thinking-in-stylex/#co-location 

styleX에서 markup하고 스타일 코드를 같이 두는 것을 원칙으로 두더라고요 
styleX를 따라 해보았습니다 제가 아직 styleX에 적응이 안 되서 이런 걸 수도...
한 번 다음단계 진행하면서 다듬어 보고 그래도 이상하면 분리해보도록 하겠습니다 🤔

2024-05-23 15:17 UTC, liswktjs commented on src/Pages/ProductDetail.tsx
> +      {...stylex.props(style.container)}
```
export declare function props(
  this: null | undefined | unknown,
  ...styles: ReadonlyArray<
    StyleXArray<
      | (null | undefined | CompiledStyles)
      | boolean
      | Readonly<[CompiledStyles, InlineStyles]>
    >
  >
): Readonly<{
  className?: string;
  style?: Readonly<{ [$$Key$$: string]: string | number }>;
}>;

```

뭔가 d.ts를 보니 스프레드 연산자를 사용함으로써 style 대응이 가능하게 해서 css in js처럼 동적으로 스타일링을 넣어주고 있는 것 같긴합니다 정적으로 이미 정의된 경우라면 반환되는  classname을 사용해도 문제 없을지도...? 🤔 이것도 좀 더 조사를 해봐야겠네요

2024-05-23 15:19 UTC, liswktjs commented on src/shared/components/Text/index.tsx
> +  zinc_500_xl_bold: {
아 제가 tailwind를 사용하면서 
tailwind css에서 기본적으로 제공해주는 color 변수명 variant를 활용해서 컬러 네이밍을 해보았습니다 

https://tailwindcss.com/docs/customizing-colors

2024-05-23 16:04 UTC, liswktjs commented on src/shared/product/api/key.ts
> +};
우선은 fsd 폴더구조를 참고해서 구현했습니다 
> https://feature-sliced.design/ 

첫 번째로, Pages 와 네이밍이 같게 feature 폴더가 있는데요 
productList page를 조합하는 컴포넌트들이 feature에 들어가 있습니다 
그래서 order detail 페이지를 구현하게 되면 feature 하위에 orderDetail 폴더가 있는 방식으로 진행될 예정입니다 
원래는 ProductDetail도 feature가 생성되어야 하는데 내용이 얼마 없어서 하나로 구현했던게 헷깔릴 수 있는 부분이였네요 
이것도 수정 같이 해서 커밋하겠습니다! 

두 번째로, shared 밑에 product 도메인이 있는 이유는 
도메인을 기준으로 묶었는데요 
서버 api와 같은 경우에는 특정 페이지에 종속 된다고 하기에는 여러 페이지에 적용될 가능성이 많기 때문에 shared하위에 위치시키는 것으로 진행했습니다 
그래서 만약, product list와 product Detail페이지에서 공통적으로 사용되는 ui 컴포넌트가 있었다면 
product 하위에 ui 폴더를 생성하여 해당 하위로 위치시킬 것 같습니다 

규모가 크지 않아서 애매하게 느껴지네요 
[1f61bd0](https://github.com/liswktjs/ts-shopping-cart/pull/1/commits/1f61bd07c1d60db69d077bb77ba0952cb8e15a03) 이 커밋으로 한 번 정리했습니다! 

```
Layout 
    - header 
    - index 

feature
  - productList
      - ShoppingProductList
      - ShoppingItem
  - productDetail
```

나머지는 파일 위치 동일합니다!

2024-06-02 05:48 UTC, soyi47 approved these changes
샐리 리뷰 반영 확인했습니다. 자세한 설명 감사해요~! 👍👍👍
수정사항은 다음 작업에 이어서 반영해보면 좋을 것 같습니다.

2024-06-02 05:48 UTC, soyi47 commented on README.md
> +### pages
오.. 기준이 있군요!! (개인적으로는 조금 어색하긴 하네요 ㅋㅋㅋ)

2024-06-02 05:48 UTC, soyi47 commented on src/Pages/ProductDetail.tsx
> +  },
오 그러네요.. 굿

2024-06-02 05:48 UTC, soyi47 commented on src/Pages/ProductDetail.tsx
> +      {...stylex.props(style.container)}
문서 상으로는 샐리가 작성해준 방식이 맞는 것 같네요 🤔
https://stylexjs.com/docs/learn/thinking-in-stylex/#low-cost-abstractions

2024-06-02 05:48 UTC, soyi47 commented on src/shared/components/Text/index.tsx
> +  zinc_500_xl_bold: {
찾아보니까 zinc 뜻 그대로 징크-아연 색상, 은회색 톤을 말하는 것 같아요.
tailwind에서도 그런 의미로 grey 계열을 zinc로 잡아둔 것 같고요!
다른 색상이라면 적절한 이름으로 바꾸면 좋을 것 같습니다.

2024-06-02 05:48 UTC, soyi47 commented on src/shared/product/api/key.ts
> +};
https://feature-sliced.design/docs/get-started/overview#basics
오 요런 방식이 있군요! 주신 문서 참고했습니다.

2024-06-02 15:13 UTC, merged